# -*- coding: utf-8 -*-
"""Samara_PQ_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtP8lU4hQzZaFod7St3_lRr4WywwdoDe
"""

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
from scipy.optimize import minimize_scalar
from scipy.optimize import root

try:
    import ezdxf
except ImportError as import_error:
    raise ImportError(
        "Missing dependency 'ezdxf'. Install it with: .venv/bin/pip install ezdxf"
    ) from import_error


DEFAULT_DXF_PATH = Path(__file__).resolve().parent / "Asa2.DXF"


class DxfWingProfile:
    """Load a single-wing contour from DXF and build a chord-width profile."""

    # pylint: disable=too-few-public-methods

    def __init__(self, dxf_path):
        self.dxf_path = Path(dxf_path)
        self.outline_points_mm = self._load_outline_points_mm()
        (
            self.outline_points_m,
            self.r0_m,
            self.rf_m,
            self.area_one_wing_m2,
            self._chord_width_m,
        ) = self._build_profile()

    def _load_outline_points_mm(self):
        """Read one contour from LWPOLYLINE, POLYLINE, or SPLINE entities."""
        if not self.dxf_path.exists():
            raise FileNotFoundError(f"DXF file not found: {self.dxf_path}")

        document = ezdxf.readfile(str(self.dxf_path))
        model_space = document.modelspace()

        lwpolylines = list(model_space.query("LWPOLYLINE"))
        if lwpolylines:
            points = [(point[0], point[1]) for point in lwpolylines[0].get_points()]
            if len(points) >= 3:
                return np.array(points, dtype=float)

        polylines = list(model_space.query("POLYLINE"))
        if polylines:
            points = [(point[0], point[1]) for point in polylines[0].points()]
            if len(points) >= 3:
                return np.array(points, dtype=float)

        splines = list(model_space.query("SPLINE"))
        if splines:
            points = []
            for spline in splines:
                points.extend((point[0], point[1]) for point in spline.control_points)
            if len(points) >= 3:
                return np.array(points, dtype=float)

        raise ValueError(
            f"No valid contour entity found in DXF: {self.dxf_path}. "
            "Expected one LWPOLYLINE, POLYLINE, or SPLINE with >= 3 points."
        )

    def _build_profile(self):
        """Convert contour into normalized coordinates and chord interpolation."""
        # pylint: disable=too-many-locals
        x_mm = self.outline_points_mm[:, 0]
        y_mm = self.outline_points_mm[:, 1]

        x_mm = x_mm - np.min(x_mm)
        y_center_mm = 0.5 * (np.min(y_mm) + np.max(y_mm))
        y_mm = y_mm - y_center_mm
        normalized_points_mm = np.column_stack([x_mm, y_mm])

        radius_max_mm = float(np.max(x_mm))
        if radius_max_mm <= 0.0:
            raise ValueError("Invalid DXF contour: maximum radius must be positive.")

        radial_centers_mm = np.linspace(0.0, radius_max_mm, 260)
        window_mm = max(radius_max_mm / 45.0, 1.0)

        chord_samples_mm = np.full_like(
            radial_centers_mm, fill_value=np.nan, dtype=float
        )
        for idx, radius_center in enumerate(radial_centers_mm):
            mask = np.abs(x_mm - radius_center) <= window_mm
            if not np.any(mask):
                nearest_index = np.argsort(np.abs(x_mm - radius_center))[:6]
                y_window = y_mm[nearest_index]
            else:
                y_window = y_mm[mask]

            if len(y_window) < 2:
                continue

            chord_samples_mm[idx] = np.max(y_window) - np.min(y_window)

        valid_mask = np.isfinite(chord_samples_mm)
        if np.count_nonzero(valid_mask) < 2:
            raise ValueError("Could not derive a valid chord distribution from DXF.")

        chord_samples_mm = np.interp(
            radial_centers_mm,
            radial_centers_mm[valid_mask],
            chord_samples_mm[valid_mask],
            left=0.0,
            right=0.0,
        )
        chord_samples_mm = np.clip(chord_samples_mm, 0.0, None)

        nonzero_mask = chord_samples_mm > 1e-6
        if not np.any(nonzero_mask):
            raise ValueError("Derived chord profile is zero across all radii.")

        r0_mm = float(radial_centers_mm[nonzero_mask][0])
        rf_mm = float(radial_centers_mm[nonzero_mask][-1])

        contour_area_mm2 = self._polygon_area_mm2(normalized_points_mm)
        chord_area_mm2 = float(np.trapezoid(chord_samples_mm, radial_centers_mm))
        area_one_wing_mm2 = (
            contour_area_mm2 if contour_area_mm2 > 0.0 else chord_area_mm2
        )

        chord_function_mm = interp1d(
            radial_centers_mm,
            chord_samples_mm,
            kind="linear",
            bounds_error=False,
            fill_value=0.0,
        )

        def chord_width_m(radial_position_m):
            radial_position_mm = np.asarray(radial_position_m, dtype=float) * 1e3
            chord_mm = chord_function_mm(radial_position_mm)
            return np.clip(chord_mm * 1e-3, 0.0, None)

        return (
            normalized_points_mm * 1e-3,
            r0_mm * 1e-3,
            rf_mm * 1e-3,
            area_one_wing_mm2 * 1e-6,
            chord_width_m,
        )

    @staticmethod
    def _polygon_area_mm2(points_mm):
        """Compute closed-polygon area with the shoelace formula."""
        if len(points_mm) < 3:
            return 0.0

        points = np.asarray(points_mm, dtype=float)
        if not np.allclose(points[0], points[-1]):
            points = np.vstack([points, points[0]])

        return 0.5 * abs(
            np.sum(points[:-1, 0] * points[1:, 1] - points[1:, 0] * points[:-1, 1])
        )

    def chord_width_m(self, radial_position_m):
        """Return local chord width w(r) in meters."""
        return self._chord_width_m(radial_position_m)


class PocketQubeSamaraWing:
    """Aerodynamic and inertial model for a PocketQube samara wing set."""

    # pylint: disable=too-many-instance-attributes,too-many-arguments,too-many-positional-arguments
    def __init__(
        self,
        dxf_path=DEFAULT_DXF_PATH,
        n_wings=4,
        radius=None,
        f_factor=0.3,
        cd0=1.0,
        k_induced=0.0,
        c_damp=0.0,
    ):
        self.dxf_path = Path(dxf_path)
        self.profile = DxfWingProfile(self.dxf_path)

        # 1. Regulatory mass and topology constraints
        self.mass = 0.250  # 250 g (PocketQube 1P regulatory maximum mass)
        self.n_wings = n_wings

        # 2. Aerodynamic geometry from DXF profile
        self.base_r0 = self.profile.r0_m
        self.base_rf = self.profile.rf_m
        self.radius = self.base_rf if radius is None else float(radius)
        self.radius_scale = max(self.radius / self.base_rf, 1e-6)

        # 3. Bluff-body and atmospheric constants
        self.pocketqube_side_m = 0.05
        self.a_face = 0.058 * 0.064
        self.cd_bluff_body = 1.05
        self.rho = 1.225

        # 4. Corrections and coefficients
        self.f_factor = f_factor
        self.cd0 = cd0
        self.k_induced = k_induced
        self.c_damp = c_damp
        self.mu_air = 1.8e-5
        self.last_reynolds_mean = np.nan

        # Aerodynamic realism tuning knobs
        self.cl_max = 1.50
        self.lift_efficiency = 0.95
        self.k_tip_loss = 0.12
        self.k_induced_drag = 0.04
        self.k_profile_loss = 0.03
        self.k_spin_drag = 0.004
        self.psi_bias_deg = 2.0
        self.psi_rate_gain = 0.004
        self.c_rot_damp = 3.0e-6

        self.i_xx = 0.0
        self.i_yy = 0.0
        self.i_zz = 0.0

        self._apply_geometry_scaling()

    def _apply_geometry_scaling(self):
        """Scale DXF geometry according to target aerodynamic radius."""
        self.r0 = self.base_r0 * self.radius_scale
        self.rf = self.base_rf * self.radius_scale
        self.wing_area_one_m2 = self.profile.area_one_wing_m2 * (self.radius_scale**2)
        self.wing_outline_points_m = self.profile.outline_points_m * self.radius_scale
        self.integration_nodes = np.linspace(self.r0, self.rf, 96)
        self.integration_chord = self.chord_width(self.integration_nodes)
        self._initialize_inertia_tensor()

    def _initialize_inertia_tensor(self):
        """Set inertia tensor approximation around pitch/yaw axes."""
        self.i_xx = 0.0
        self.i_yy = (1 / 3) * self.f_factor * self.mass * (self.radius**2)
        self.i_zz = self.i_yy

    def update_geometry(self, radius, f_factor, cd0, n_wings):
        """Update scaled geometry and inertial factors for optimization iterations."""
        self.radius = float(radius)
        self.radius_scale = max(self.radius / self.base_rf, 1e-6)
        self.f_factor = f_factor
        self.cd0 = cd0
        self.n_wings = n_wings
        self._apply_geometry_scaling()

    def chord_width(self, radial_position_m):
        """Scaled chord width function w(r) from the DXF contour."""
        radial_array = np.asarray(radial_position_m, dtype=float)
        chord_result = np.zeros_like(radial_array, dtype=float)

        valid_mask = (radial_array > self.r0) & (radial_array < self.rf)
        if np.any(valid_mask):
            base_radius = radial_array[valid_mask] / self.radius_scale
            base_chord = np.asarray(
                self.profile.chord_width_m(base_radius), dtype=float
            )
            chord_result[valid_mask] = np.clip(
                base_chord * self.radius_scale, 0.0, None
            )

        if np.isscalar(radial_position_m):
            return float(chord_result)
        return chord_result

    # pylint: disable=too-many-arguments,too-many-positional-arguments
    def _local_kinematics(self, r, theta, theta_dot, phi_dot, v_0):
        """Compute local freestream magnitude and angle of attack."""
        v_py = r * phi_dot * np.cos(theta)
        # Simplified inflow: optional induced velocity scales with local rotational speed.
        v_induced = self.k_induced * np.abs(r * phi_dot)
        v_pz = v_0 * np.cos(theta) + r * theta_dot + v_induced
        u_inf_sq = v_py**2 + v_pz**2
        alpha = np.arctan2(-v_pz, v_py)
        return u_inf_sq, alpha

    def vertical_alignment_factor(self, theta, theta_dot, phi_dot):
        """Approximate loss from small roll misalignment without full 6DOF."""
        _ = phi_dot
        psi_eff_deg = np.clip(
            self.psi_bias_deg + self.psi_rate_gain * np.degrees(np.abs(theta_dot)),
            0.0,
            20.0,
        )
        psi_eff = np.radians(psi_eff_deg)
        return np.cos(theta) * np.cos(psi_eff)

    # pylint: disable=too-many-locals
    def compute_forces_and_moments(self, theta, theta_dot, phi_dot, v_0):
        """Compute aerodynamic force and moment components for one wing."""

        radial = self.integration_nodes
        chord_local = self.integration_chord
        radial_ratio = np.clip(radial / max(self.rf, 1e-6), 0.0, 1.0)

        u_inf_sq, alpha = self._local_kinematics(radial, theta, theta_dot, phi_dot, v_0)
        cl_raw = 2.0 * np.pi * np.sin(alpha)
        cl = self.cl_max * np.tanh(cl_raw / self.cl_max)

        tip_factor = np.clip(1.0 - self.k_tip_loss * (radial_ratio**2), 0.55, 1.0)
        cl_eff = cl * self.lift_efficiency * tip_factor

        cd_base = self.cd0 + cl_eff * np.sin(alpha)
        cd_induced = self.k_induced_drag * (cl_eff**2)
        cd_profile = self.k_profile_loss * (1.0 - tip_factor)
        spin_ratio = (
            np.abs(phi_dot) * max(self.rf, 1e-4) / max(np.sqrt(np.mean(u_inf_sq)), 1e-3)
        )
        cd_spin = self.k_spin_drag * (spin_ratio**2)
        cd = np.clip(cd_base + cd_induced + cd_profile + cd_spin, self.cd0, 4.0)

        local_speed = np.sqrt(np.clip(u_inf_sq, 0.0, None))
        reynolds = self.rho * local_speed * chord_local / self.mu_air
        self.last_reynolds_mean = float(np.mean(reynolds))

        force_scale = 0.5 * self.rho * chord_local * u_inf_sq
        integrand_fy3 = force_scale * (np.sin(alpha) * cl_eff - np.cos(alpha) * cd)
        integrand_fz3 = force_scale * (np.cos(alpha) * cl_eff + np.sin(alpha) * cd)

        f_y3 = float(np.trapezoid(integrand_fy3, radial))
        f_z3 = float(np.trapezoid(integrand_fz3, radial))
        m_y3 = float(np.trapezoid(-radial * integrand_fz3, radial))
        m_z3 = float(np.trapezoid(radial * integrand_fy3, radial))
        m_z3 -= self.c_rot_damp * phi_dot * np.abs(phi_dot)

        return f_y3, f_z3, m_y3, m_z3


class PocketQubeFlightDynamics:
    """Dynamic model and integration utilities for samara descent."""

    def __init__(self, pq_wing):
        self.wing = pq_wing
        self.g = 9.81

    # pylint: disable=too-many-locals
    def _state_derivatives(self, t, state):
        _ = t
        theta, theta_dot, phi_dot, v_0, z_alt = state
        _ = z_alt

        cos_theta = np.clip(np.cos(theta), 1e-3, None)
        tan_theta = np.tan(np.clip(theta, -np.pi / 2 + 1e-3, np.pi / 2 - 1e-3))

        f_y3_1, f_z3_1, m_y3_1, m_z3_1 = self.wing.compute_forces_and_moments(
            theta, theta_dot, phi_dot, v_0
        )

        n_wings = self.wing.n_wings
        f_y3 = f_y3_1 * n_wings
        f_z3_wings = f_z3_1 * n_wings
        m_y3 = m_y3_1 * n_wings
        m_z3 = m_z3_1 * n_wings
        _ = f_y3

        m_y3 -= self.wing.c_damp * theta_dot
        m_z3 -= self.wing.c_damp * phi_dot

        f_drag_cube = (
            0.5 * self.wing.rho * (v_0**2) * self.wing.a_face * self.wing.cd_bluff_body
        )
        f_z3_total = f_z3_wings + f_drag_cube
        vertical_factor = self.wing.vertical_alignment_factor(theta, theta_dot, phi_dot)

        d_theta = theta_dot
        d_theta_dot = (-m_y3 / self.wing.i_yy) - (phi_dot**2) * np.sin(
            theta
        ) * cos_theta
        d_phi_dot = (
            m_z3 / (self.wing.i_yy * cos_theta)
        ) + 2 * phi_dot * theta_dot * tan_theta
        d_v0 = -self.g + (f_z3_total * vertical_factor) / self.wing.mass
        d_z_alt = v_0

        return [d_theta, d_theta_dot, d_phi_dot, d_v0, d_z_alt]

    # pylint: disable=too-many-locals
    def calculate_steady_state(self, preferred_vf=None):
        """Solve for a steady operating point using a multi-start strategy."""

        def system_equations(state_vars):
            theta, phi_dot, v_0 = state_vars
            state = [theta, 0.0, phi_dot, v_0, 1000.0]
            derivs = self._state_derivatives(0, state)
            return np.array([derivs[1], derivs[2], derivs[3]], dtype=float)

        theta_guesses = np.radians([5.0, 10.0, 20.0, 30.0, 45.0])
        phi_guesses = [2.0, 5.0, 10.0, 20.0, 40.0, 80.0]
        v0_guesses = [-5.0, -10.0, -15.0, -20.0, -25.0, -35.0, -50.0]

        best_solution = None
        best_score = np.inf

        for theta_guess in theta_guesses:
            for phi_guess in phi_guesses:
                for v0_guess in v0_guesses:
                    solution = root(
                        system_equations,
                        [theta_guess, phi_guess, v0_guess],
                        method="hybr",
                    )
                    if not solution.success:
                        continue

                    theta_sol, phi_dot_sol, v0_sol = solution.x
                    residual_norm = float(np.linalg.norm(system_equations(solution.x)))
                    if preferred_vf is None:
                        score = residual_norm
                    else:
                        score = abs(v0_sol - preferred_vf) + 0.05 * residual_norm

                    if score < best_score:
                        best_score = score
                        best_solution = (theta_sol, 0.0, phi_dot_sol, v0_sol)

        return best_solution

    def simulate_drop(self, initial_conditions=None, t_span=(0, 150.0), max_step=0.05):
        """Run time-domain drop simulation until ground impact."""
        if initial_conditions is None:
            initial_conditions = [np.radians(20), 0.0, 0.1, 0.0, 1000.0]

        def hit_ground(_, state_vector):
            return state_vector[4]

        hit_ground.terminal = True
        hit_ground.direction = -1

        print("-> Propagating ballistic trajectory (this may take a few seconds)...")
        return solve_ivp(
            fun=self._state_derivatives,
            t_span=t_span,
            y0=initial_conditions,
            method="RK45",
            events=hit_ground,
            max_step=max_step,
        )


class PocketQubeLRRVisualizer:
    """Generate LRR-oriented plots from simulation output."""

    # pylint: disable=too-few-public-methods
    def __init__(self, simulation_solution, output_dir="extras/wing-analisys"):
        self.t = simulation_solution.t
        self.theta = np.degrees(simulation_solution.y[0])
        self.theta_dot = simulation_solution.y[1]
        self.phi_dot = simulation_solution.y[2] / (2 * np.pi)
        self.v0 = simulation_solution.y[3]
        self.z_alt = simulation_solution.y[4]
        self.output_dir = Path(output_dir)

    def generate_lrr_report(self, show_plot=False):
        """Render a 2x2 diagnostics dashboard for descent certification."""
        fig, axs = plt.subplots(2, 2, figsize=(14, 10))
        fig.suptitle(
            "LRR Certification Report - PocketQube 1P Autorotative",
            fontsize=16,
            fontweight="bold",
        )

        axs[0, 0].plot(self.t, self.z_alt, "b-", linewidth=2)
        axs[0, 0].set_title("Descent Profile (AGL Altitude)")
        axs[0, 0].set_ylabel("Altitude (m)")
        axs[0, 0].axhline(
            1500,
            color="red",
            linestyle="--",
            label="LASC Deployment Ceiling (1500 m)",
        )
        axs[0, 0].grid(True)
        axs[0, 0].legend()

        axs[0, 1].plot(
            self.t, self.v0, "k-", linewidth=2, label="Simulated Vertical Speed"
        )
        axs[0, 1].set_title("Descent Rate & LASC Target")
        axs[0, 1].set_ylabel("Vertical Speed (m/s)")
        axs[0, 1].axhspan(
            -45,
            -20,
            color="green",
            alpha=0.2,
            label="Safe Operational Window (20-45 m/s)",
        )
        axs[0, 1].axhline(
            -25,
            color="darkgreen",
            linestyle=":",
            linewidth=2,
            label="Tuning Target (-25 m/s)",
        )
        axs[0, 1].grid(True)
        axs[0, 1].legend()

        axs[1, 0].plot(self.t, self.theta, "m-", linewidth=2)
        axs[1, 0].set_title("Pitch / Wing Conicity")
        axs[1, 0].set_ylabel("Angle (degrees)")
        axs[1, 0].set_xlabel("Time (s)")
        axs[1, 0].grid(True)

        axs[1, 1].plot(self.t, self.phi_dot, "g-", linewidth=2)
        axs[1, 1].set_title("Gyroscopic Balance (Satellite Spin)")
        axs[1, 1].set_ylabel("Yaw Rate (rev/s)")
        axs[1, 1].set_xlabel("Time (s)")
        axs[1, 1].grid(True)

        plt.tight_layout(rect=[0, 0.03, 1, 0.95])
        self.output_dir.mkdir(parents=True, exist_ok=True)
        report_path = self.output_dir / "samara_pq_lrr_report.png"
        fig.savefig(report_path, dpi=150, bbox_inches="tight")
        print(f"Saved LRR plot:    {report_path}")

        if show_plot:
            plt.show()
        else:
            plt.close(fig)


# pylint: disable=too-many-locals
def plot_frontal_area_system(wing, output_dir="extras/wing-analisys"):
    """Save a dimensional frontal-view sketch with body and rotated DXF wings."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(8, 8))

    body_side_m = wing.pocketqube_side_m
    body_half_m = body_side_m / 2.0
    body_xy = np.array(
        [
            [-body_half_m, -body_half_m],
            [body_half_m, -body_half_m],
            [body_half_m, body_half_m],
            [-body_half_m, body_half_m],
        ]
    )
    ax.fill(body_xy[:, 0] * 1e3, body_xy[:, 1] * 1e3, color="#264653", alpha=0.45)
    ax.plot(
        np.r_[body_xy[:, 0], body_xy[0, 0]] * 1e3,
        np.r_[body_xy[:, 1], body_xy[0, 1]] * 1e3,
        color="#264653",
        linewidth=2,
    )

    for wing_idx in range(wing.n_wings):
        angle_rad = wing_idx * (2.0 * np.pi / wing.n_wings)
        rotation_matrix = np.array(
            [
                [np.cos(angle_rad), -np.sin(angle_rad)],
                [np.sin(angle_rad), np.cos(angle_rad)],
            ]
        )
        wing_polygon = wing.wing_outline_points_m @ rotation_matrix.T

        ax.fill(
            wing_polygon[:, 0] * 1e3,
            wing_polygon[:, 1] * 1e3,
            color="#2a9d8f",
            alpha=0.55,
        )
        ax.plot(
            np.r_[wing_polygon[:, 0], wing_polygon[0, 0]] * 1e3,
            np.r_[wing_polygon[:, 1], wing_polygon[0, 1]] * 1e3,
            color="#1f7f76",
            linewidth=1.2,
        )

    axis_limit_mm = max(wing.rf, body_half_m) * 1e3 * 1.35
    ax.set_xlim(-axis_limit_mm, axis_limit_mm)
    ax.set_ylim(-axis_limit_mm, axis_limit_mm)
    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, alpha=0.25)
    ax.set_xlabel("X (mm)")
    ax.set_ylabel("Y (mm)")

    body_area_cm2 = body_side_m * body_side_m * 1e4
    wing_area_total_cm2 = wing.n_wings * wing.wing_area_one_m2 * 1e4
    total_area_cm2 = body_area_cm2 + wing_area_total_cm2
    ax.set_title(
        "Frontal Area Dimensional Representation\n"
        f"Body: {body_area_cm2:.2f} cm² | Wings: {wing_area_total_cm2:.2f} cm² | "
        f"Total: {total_area_cm2:.2f} cm²"
    )
    ax.text(0, 0, "PocketQube\n50 x 50 mm", ha="center", va="center", fontsize=10)

    frontal_path = out_dir / "samara_pq_frontal_area.png"
    fig.savefig(frontal_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved frontal area: {frontal_path}")


class PocketQubeSamaraOptimizer:
    """Numerical optimizer for topology-specific descent tuning."""

    # pylint: disable=too-few-public-methods
    def __init__(self, flight_solver, target_vf=-25.0):
        self.solver = flight_solver
        self.target_vf = target_vf
        self._impact_cache = {}

    def _cost_function_radius(self, radius, n_wings, f_factor, cd0):
        """Objective: squared error using radius as the only decision variable."""
        self.solver.wing.update_geometry(radius, f_factor, cd0, n_wings)
        steady_states = self.solver.calculate_steady_state(preferred_vf=self.target_vf)
        if steady_states is None:
            return 1e6
        return (steady_states[3] - self.target_vf) ** 2

    def optimize_radius_for_topology(self, n_wings):
        """Optimize only aerodynamic radius for a fixed configuration."""
        print(
            f"\n[ENGINEERING] Solving required radius for topology N={n_wings} wings..."
        )

        f_factor_fixed = self.solver.wing.f_factor
        cd0_fixed = self.solver.wing.cd0
        base_radius = self.solver.wing.base_rf
        bounds = (0.10 * base_radius, 1.80 * base_radius)

        result = minimize_scalar(
            self._cost_function_radius,
            args=(n_wings, f_factor_fixed, cd0_fixed),
            method="bounded",
            bounds=bounds,
            options={"xatol": 1e-4, "maxiter": 120},
        )

        if result.success:
            radius_opt = float(result.x)
            velocity_error = float(np.sqrt(max(result.fun, 0.0)))
            print("[SUCCESS] Radius target solved!")
            print(f" -> Required aerodynamic radius: {radius_opt * 100:.2f} cm")
            print(f" -> Fixed inertia factor (f): {f_factor_fixed:.3f}")
            print(f" -> Fixed vortex requirement (Cd0): {cd0_fixed:.3f}")
            print(f" -> Residual |vf - target|: {velocity_error:.3f} m/s")
            return radius_opt

        print("[FAILURE] Could not solve radius for the requested target vf.")
        return None

    @staticmethod
    def _impact_vertical_velocity(solution):
        """Get vertical velocity at impact event or fallback to final sample."""
        if solution.t_events and len(solution.t_events[0]) > 0:
            return float(solution.y_events[0][0][3]), True
        return float(solution.y[3][-1]), False

    # pylint: disable=too-many-arguments,too-many-positional-arguments
    def _cost_function_radius_impact(
        self,
        radius,
        n_wings,
        f_factor,
        cd0,
        target_impact_vf,
        sim_t_span,
        sim_max_step,
    ):
        """Objective based on impact velocity mismatch from time simulation."""
        cache_key = (
            round(float(radius), 6),
            n_wings,
            round(float(f_factor), 4),
            round(float(cd0), 4),
            round(float(target_impact_vf), 3),
            sim_t_span,
            round(float(sim_max_step), 3),
        )
        if cache_key in self._impact_cache:
            return self._impact_cache[cache_key]

        self.solver.wing.update_geometry(radius, f_factor, cd0, n_wings)
        solution = self.solver.simulate_drop(t_span=sim_t_span, max_step=sim_max_step)
        impact_vz, impact_detected = self._impact_vertical_velocity(solution)
        error_sq = (impact_vz - target_impact_vf) ** 2

        if impact_detected:
            score = error_sq
        else:
            # Prefer solutions that actually hit the ground inside t_span.
            altitude_penalty = abs(float(solution.y[4][-1])) * 0.01
            score = error_sq + altitude_penalty

        self._impact_cache[cache_key] = score
        return score

    def optimize_radius_for_impact(
        self,
        n_wings,
        target_impact_vf=-25.0,
        sim_t_span=(0.0, 600.0),
        sim_max_step=0.2,
    ):
        """Optimize radius to match target impact vertical velocity."""
        print("\n[ENGINEERING] Solving required radius for target impact vf=")
        print(f"{target_impact_vf:.2f} m/s...")

        f_factor_fixed = self.solver.wing.f_factor
        cd0_fixed = self.solver.wing.cd0
        base_radius = self.solver.wing.base_rf
        bounds = (0.08 * base_radius, 2.00 * base_radius)

        self._impact_cache.clear()
        result = minimize_scalar(
            self._cost_function_radius_impact,
            args=(
                n_wings,
                f_factor_fixed,
                cd0_fixed,
                target_impact_vf,
                sim_t_span,
                sim_max_step,
            ),
            method="bounded",
            bounds=bounds,
            options={"xatol": 1e-4, "maxiter": 45},
        )

        if result.success:
            radius_opt = float(result.x)
            self.solver.wing.update_geometry(
                radius_opt, f_factor_fixed, cd0_fixed, n_wings
            )
            verification = self.solver.simulate_drop(
                t_span=sim_t_span, max_step=sim_max_step
            )
            impact_vz, impact_detected = self._impact_vertical_velocity(verification)
            velocity_error = abs(impact_vz - target_impact_vf)

            print("[SUCCESS] Impact-velocity radius solved!")
            print(f" -> Required aerodynamic radius: {radius_opt * 100:.2f} cm")
            print(f" -> Impact event detected: {impact_detected}")
            print(f" -> Impact vertical velocity: {impact_vz:.3f} m/s")
            print(f" -> Residual |vf_impact - target|: {velocity_error:.3f} m/s")
            return radius_opt

        print("[FAILURE] Could not solve radius for target impact velocity.")
        return None


class PocketQubeMissionReporter:
    """Create mission report artifacts and print key impact metrics."""

    # pylint: disable=too-few-public-methods
    def __init__(self, wing, simulation_solution):
        self.wing = wing
        self.solution = simulation_solution
        self.initial_altitude_m = float(simulation_solution.y[4][0])

    def _extract_impact_state(self):
        """Return the state at impact or the final simulated sample."""
        impact_detected = bool(
            self.solution.t_events and len(self.solution.t_events[0]) > 0
        )

        if impact_detected:
            return {
                "impact_detected": True,
                "time_s": float(self.solution.t_events[0][0]),
                "theta_rad": float(self.solution.y_events[0][0][0]),
                "theta_dot_rads": float(self.solution.y_events[0][0][1]),
                "phi_dot_rads": float(self.solution.y_events[0][0][2]),
                "v_vertical_ms": float(self.solution.y_events[0][0][3]),
                "altitude_m": float(self.solution.y_events[0][0][4]),
            }

        return {
            "impact_detected": False,
            "time_s": float(self.solution.t[-1]),
            "theta_rad": float(self.solution.y[0][-1]),
            "theta_dot_rads": float(self.solution.y[1][-1]),
            "phi_dot_rads": float(self.solution.y[2][-1]),
            "v_vertical_ms": float(self.solution.y[3][-1]),
            "altitude_m": float(self.solution.y[4][-1]),
        }

    def build_summary(self):
        """Compute impact, angular, and geometry metrics."""
        impact_state = self._extract_impact_state()
        impact_speed_ms = abs(impact_state["v_vertical_ms"])
        impact_energy_j = 0.5 * self.wing.mass * (impact_speed_ms**2)
        omega_rads = abs(impact_state["phi_dot_rads"])
        omega_rpm = omega_rads * 60.0 / (2.0 * np.pi)
        initial_potential_energy_j = self.wing.mass * 9.81 * self.initial_altitude_m
        dissipated_energy_j = initial_potential_energy_j - impact_energy_j
        energy_non_physical = dissipated_energy_j < -1e-6

        body_area_cm2 = self.wing.pocketqube_side_m * self.wing.pocketqube_side_m * 1e4
        wing_area_one_cm2 = self.wing.wing_area_one_m2 * 1e4
        wing_area_total_cm2 = self.wing.n_wings * wing_area_one_cm2

        return {
            "mass_kg": float(self.wing.mass),
            "geometry": {
                "dxf_file": str(self.wing.dxf_path),
                "n_wings": int(self.wing.n_wings),
                "radius_scale": float(self.wing.radius_scale),
                "root_radius_m": float(self.wing.r0),
                "tip_radius_m": float(self.wing.rf),
                "wing_area_one_cm2": float(wing_area_one_cm2),
                "wing_area_total_cm2": float(wing_area_total_cm2),
                "body_square_area_cm2": float(body_area_cm2),
                "total_frontal_area_cm2": float(body_area_cm2 + wing_area_total_cm2),
            },
            "impact": {
                "detected": impact_state["impact_detected"],
                "time_s": impact_state["time_s"],
                "altitude_m": impact_state["altitude_m"],
                "vertical_velocity_ms": impact_state["v_vertical_ms"],
                "speed_magnitude_ms": impact_speed_ms,
                "kinetic_energy_j": impact_energy_j,
            },
            "energy": {
                "initial_potential_j": float(initial_potential_energy_j),
                "final_kinetic_j": float(impact_energy_j),
                "dissipated_j": float(dissipated_energy_j),
                "non_physical": bool(energy_non_physical),
            },
            "angular": {
                "theta_deg": float(np.degrees(impact_state["theta_rad"])),
                "theta_dot_rads": impact_state["theta_dot_rads"],
                "phi_dot_rads": impact_state["phi_dot_rads"],
                "spin_rpm": float(omega_rpm),
            },
        }

    def print_summary(self, summary):
        """Print key report values in a compact engineering format."""
        print("\n" + "=" * 70)
        print("IMPACT REPORT")
        print("=" * 70)
        status = (
            "GROUND IMPACT DETECTED"
            if summary["impact"]["detected"]
            else "NO IMPACT EVENT"
        )
        print(f"DXF profile:              {summary['geometry']['dxf_file']}")
        print(f"Status: {status}")
        print(f"Impact time:              {summary['impact']['time_s']:.2f} s")
        print(f"Altitude at final state:  {summary['impact']['altitude_m']:.2f} m")
        print(
            f"Impact speed |v|:         {summary['impact']['speed_magnitude_ms']:.2f} m/s"
        )
        print(
            f"Vertical speed vz:        {summary['impact']['vertical_velocity_ms']:.2f} m/s"
        )
        print(
            f"Impact kinetic energy:    {summary['impact']['kinetic_energy_j']:.2f} J"
        )
        print(
            f"Angular speed phi_dot:    {summary['angular']['phi_dot_rads']:.2f} rad/s"
        )
        print(f"Angular speed spin:       {summary['angular']['spin_rpm']:.2f} rpm")
        print(f"Mean Reynolds number:     {self.wing.last_reynolds_mean:.0f}")
        print(
            f"Initial potential energy: {summary['energy']['initial_potential_j']:.2f} J"
        )
        print(f"Final kinetic energy:     {summary['energy']['final_kinetic_j']:.2f} J")
        print(f"Dissipated energy:        {summary['energy']['dissipated_j']:.2f} J")
        if summary["energy"]["non_physical"]:
            print("[WARNING] Non-physical energy balance detected.")
        print(
            f"Total frontal area:       {summary['geometry']['total_frontal_area_cm2']:.2f} cm²"
        )
        print("=" * 70)

    def save_report_files(self, summary, output_dir="extras/wing-analisys"):
        """Persist report in JSON and TXT files."""
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        json_path = out_dir / "samara_pq_impact_report.json"
        txt_path = out_dir / "samara_pq_impact_report.txt"

        with open(json_path, "w", encoding="utf-8") as handle:
            json.dump(summary, handle, indent=2)

        with open(txt_path, "w", encoding="utf-8") as handle:
            status_text = (
                "GROUND IMPACT DETECTED"
                if summary["impact"]["detected"]
                else "NO IMPACT EVENT"
            )
            handle.write("=" * 70 + "\n")
            handle.write("IMPACT REPORT\n")
            handle.write("=" * 70 + "\n")
            handle.write(
                f"DXF profile:             {summary['geometry']['dxf_file']}\n"
            )
            handle.write(f"Status: {status_text}\n")
            handle.write(
                f"Impact time:             {summary['impact']['time_s']:.2f} s\n"
            )
            handle.write(
                f"Altitude at final state: {summary['impact']['altitude_m']:.2f} m\n"
            )
            handle.write(
                f"Impact speed |v|:        {summary['impact']['speed_magnitude_ms']:.2f} m/s\n"
            )
            handle.write(
                f"Vertical speed vz:       {summary['impact']['vertical_velocity_ms']:.2f} m/s\n"
            )
            handle.write(
                f"Impact kinetic energy:   {summary['impact']['kinetic_energy_j']:.2f} J\n"
            )
            handle.write(
                f"Angular speed phi_dot:   {summary['angular']['phi_dot_rads']:.2f} rad/s\n"
            )
            handle.write(
                f"Angular speed spin:      {summary['angular']['spin_rpm']:.2f} rpm\n"
            )
            handle.write(
                f"Mean Reynolds number:    {self.wing.last_reynolds_mean:.0f}\n"
            )
            handle.write(
                f"Initial potential energy: {summary['energy']['initial_potential_j']:.2f} J\n"
            )
            handle.write(
                f"Final kinetic energy:     {summary['energy']['final_kinetic_j']:.2f} J\n"
            )
            handle.write(
                f"Dissipated energy:        {summary['energy']['dissipated_j']:.2f} J\n"
            )
            if summary["energy"]["non_physical"]:
                handle.write("WARNING: Non-physical energy balance detected.\n")
            handle.write(
                "Total frontal area:      "
                f"{summary['geometry']['total_frontal_area_cm2']:.2f} cm²\n"
            )

        print(f"Saved JSON report: {json_path}")
        print(f"Saved TXT report:  {txt_path}")


print("==========================================================")
print(" LASC POCKETQUBE 1P - SRAB PIPELINE INITIALIZED ")
print("==========================================================")


def main():
    """Execute calibration, simulation, and visualization pipeline."""
    print(f"Using default wing profile: {DEFAULT_DXF_PATH}")
    sim_t_span = (0.0, 600.0)
    sim_max_step = 0.2

    wing = PocketQubeSamaraWing(dxf_path=DEFAULT_DXF_PATH, n_wings=4)
    solver = PocketQubeFlightDynamics(wing)

    optimizer = PocketQubeSamaraOptimizer(solver, target_vf=-25.0)
    optimal_radius = optimizer.optimize_radius_for_impact(
        n_wings=4,
        target_impact_vf=-25.0,
        sim_t_span=sim_t_span,
        sim_max_step=sim_max_step,
    )

    if optimal_radius is not None:
        wing.update_geometry(optimal_radius, wing.f_factor, wing.cd0, n_wings=4)

        solution = solver.simulate_drop(t_span=sim_t_span, max_step=sim_max_step)

        reporter = PocketQubeMissionReporter(wing, solution)
        summary = reporter.build_summary()
        reporter.print_summary(summary)
        reporter.save_report_files(summary)

        plot_frontal_area_system(wing)

        visualizer = PocketQubeLRRVisualizer(solution)
        visualizer.generate_lrr_report()


if __name__ == "__main__":
    main()
